server:
  port: 9002
  servlet:
    context-path: /auth

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.232.221:3306/test1
    #url: jdbc:mysql://mysql-container:3306/moonrise
    username: ssafy
    password: qwer1234
  jpa:
    database: mysql   # ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # ?? ?? ??

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  # org.hibernate.type: trace #??? ?? 2.x, hibernate5
  # org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6